# Generated by Django 3.0.5 on 2020-07-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200715_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ManyToManyField(to='post.Category'),
        ),
    ]
