# Generated by Django 3.0.5 on 2020-07-17 14:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200716_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='content',
            field=tinymce.models.HTMLField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ManyToManyField(to='post.Category'),
        ),
    ]
