# Generated by Django 3.0.5 on 2020-07-17 16:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200717_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ManyToManyField(to='post.Category'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
