# Generated by Django 3.0.5 on 2020-07-18 20:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200718_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ManyToManyField(to='post.Category'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
