# Generated by Django 3.0.5 on 2020-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20200720_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ManyToManyField(to='post.Category'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
