# Generated by Django 3.0.5 on 2020-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20200726_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='categories',
            field=models.ManyToManyField(to='post.Category'),
        ),
    ]
